// Regenerates src/fonts/*.ts from fonts/*.ttf as base64 modules.
//
// Base64 modules work identically on Node and workerd (no fs, no vite asset
// rules) — the bytes ship in the bundle either way. Base64 costs ~33% raw,
// which gzip mostly claws back. The .ttf sources are variable fonts instanced
// to a single weight and subsetted to Latin, so they stay small.
//
// Run: pnpm --filter @myemdash/og embed-fonts
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { basename, join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const srcDir = join(root, "fonts");
const outDir = join(root, "src", "fonts");
await mkdir(outDir, { recursive: true });

const files = (await readdir(srcDir)).filter((f) => f.endsWith(".ttf")).sort();
if (files.length === 0) throw new Error("No .ttf files in fonts/");

const entries = [];
for (const file of files) {
	const name = basename(file, ".ttf");
	const ident = name.replaceAll("-", "_");
	const b64 = (await readFile(join(srcDir, file))).toString("base64");
	await writeFile(
		join(outDir, `${name}.ts`),
		`// Generated by scripts/embed-fonts.mjs from fonts/${file} — do not edit.\nexport default\n\t"${b64}";\n`,
	);
	entries.push({ name, ident });
}

const index = [
	"// Generated by scripts/embed-fonts.mjs — do not edit.",
	...entries.map((e) => `import ${e.ident} from "./${e.name}.js";`),
	"",
	"function decode(b64: string): Uint8Array {",
	"\tconst bin = atob(b64);",
	"\tconst out = new Uint8Array(bin.length);",
	"\tfor (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);",
	"\treturn out;",
	"}",
	"",
	"/** Font bytes, decoded lazily so unused faces cost nothing at import time. */",
	"export const fontFiles: Record<string, () => Uint8Array> = {",
	...entries.map((e) => `\t"${e.name}": () => decode(${e.ident}),`),
	"};",
	"",
].join("\n");

await writeFile(join(outDir, "index.ts"), index);
console.log(`Embedded ${entries.length} fonts:`, entries.map((e) => e.name).join(", "));
