// Generated by scripts/embed-fonts.mjs — do not edit.
import CormorantGaramond_Light from "./CormorantGaramond-Light.js";
import CormorantGaramond_LightItalic from "./CormorantGaramond-LightItalic.js";
import JosefinSans_SemiBold from "./JosefinSans-SemiBold.js";

function decode(b64: string): Uint8Array {
	const bin = atob(b64);
	const out = new Uint8Array(bin.length);
	for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
	return out;
}

/** Font bytes, decoded lazily so unused faces cost nothing at import time. */
export const fontFiles: Record<string, () => Uint8Array> = {
	"CormorantGaramond-Light": () => decode(CormorantGaramond_Light),
	"CormorantGaramond-LightItalic": () => decode(CormorantGaramond_LightItalic),
	"JosefinSans-SemiBold": () => decode(JosefinSans_SemiBold),
};
